// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package package1;

public interface hadCovidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hadCovid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hadC = 1;</code>
   */
  java.lang.String getHadC();
  /**
   * <code>string hadC = 1;</code>
   */
  com.google.protobuf.ByteString
      getHadCBytes();
}
