// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package package1;

public interface riskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:risk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 risk = 1;</code>
   */
  int getRisk();
}
