// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package package1;

public interface userIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
