// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package package3;

public interface availableDateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:availableDate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string available = 1;</code>
   */
  java.lang.String getAvailable();
  /**
   * <code>string available = 1;</code>
   */
  com.google.protobuf.ByteString
      getAvailableBytes();
}
