// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package package3;

public final class outerClass3 {
  private outerClass3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hadVaccination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hadVaccination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_availableDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_availableDate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\"\024\n\006userId\022\n\n\002id\030\001 \001(\005\"%" +
      "\n\016hadVaccination\022\023\n\013vaccination\030\001 \001(\010\"\t\n" +
      "\007request\"\"\n\ravailableDate\022\021\n\tavailable\030\001" +
      " \001(\t2o\n\013Vaccination\022/\n\023vaccination_histo" +
      "ry\022\007.userId\032\017.hadVaccination\022/\n\023see_avai" +
      "lable_dates\022\010.request\032\016.availableDateB\031\n" +
      "\010package3B\013outerClass3P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_hadVaccination_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hadVaccination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hadVaccination_descriptor,
        new java.lang.String[] { "Vaccination", });
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { });
    internal_static_availableDate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_availableDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_availableDate_descriptor,
        new java.lang.String[] { "Available", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
