// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package package3;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request)
    com.google.protobuf.MessageOrBuilder {
}
