// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package package2;

public interface ifSafeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ifSafe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool safe = 1;</code>
   */
  boolean getSafe();
}
