// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package package2;

public final class outerClass2 {
  private outerClass2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_positions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_positions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thanks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thanks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifSafe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifSafe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\"\036\n\tpositions\022\021\n\tpositio" +
      "n1\030\001 \001(\t\"\027\n\006thanks\022\r\n\005thank\030\001 \001(\t\"\t\n\007req" +
      "uest\"\026\n\006ifSafe\022\014\n\004safe\030\001 \001(\0102\211\001\n\tRisk_Fr" +
      "ee\022(\n\017covid_positions\022\n.positions\032\007.than" +
      "ks(\001\022$\n\nsafe_zones\022\010.request\032\n.positions" +
      "0\001\022,\n\021inside_safe_zones\022\n.positions\032\007.if" +
      "Safe(\0010\001B\031\n\010package2B\013outerClass2P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_positions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_positions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_positions_descriptor,
        new java.lang.String[] { "Position1", });
    internal_static_thanks_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_thanks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thanks_descriptor,
        new java.lang.String[] { "Thank", });
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { });
    internal_static_ifSafe_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ifSafe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifSafe_descriptor,
        new java.lang.String[] { "Safe", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
