// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package package2;

public interface positionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:positions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string position1 = 1;</code>
   */
  java.lang.String getPosition1();
  /**
   * <code>string position1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getPosition1Bytes();
}
