// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package package2;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request)
    com.google.protobuf.MessageOrBuilder {
}
